version: '2'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - "TZ=Europe/Moscow"
      - "POSTGRES_USER=docker"
      - "POSTGRES_PASSWORD=docker"
      - "APP_DB_NAME=sparkdeveloper"
    ports:
      - "5432:5432"
    volumes:
      - "./db:/docker-entrypoint-initdb.d/"
